all:
	g++ -Wall -g -std=c++17 test_pipe.cpp -o test_pipe
	g++ -Wall -g -std=c++17 test_mmap.cpp -o test_mmap
	g++ -Wall -g -std=c++17 test_process_copy.cpp -o test_process_copy
	g++ -Wall -g -std=c++17 test_file_copy.cpp -o test_file_copy

clean:
	rm -rf test_pipe test_mmap test_process_copy test_file_copy