all:
	@# g++ -Wall -g -std=c++17 test_prime.cpp -o test_prime -lpthread
	@# g++ -Wall -g -std=c++17 test_prime_cross.cpp -o test_prime_cross -lpthread
	@# g++ -Wall -g -std=c++17 test_mutex_num.cpp -o test_mutex_num -lpthread
	@# g++ -Wall -g -std=c++17 test_prime_pool.cpp -o test_prime_pool -lpthread
	g++ -Wall -g -std=c++17 test_cond_parking.cpp -o test_cond_parking -lpthread

clean:
	rm -rf test_prime test_prime_cross test_mutex_num test_prime_pool test_cond_parking