all:
	# g++ -Wall -g -std=c++17 test_sigaction.cpp -o test_sigaction
	# g++ -Wall -g -std=c++17 test_cal_clock.cpp -o test_cal_clock
	# g++ -Wall -g -std=c++17 test_cal_alarm.cpp -o test_cal_alarm

	# g++ -Wall -g -std=c++17 test_print_sleep.cpp -o test_print_sleep
	# g++ -Wall -g -std=c++17 test_print_alarm.cpp -o test_print_alarm
	# g++ -Wall -g -std=c++17 test_print_setitimer.cpp -o test_print_setitimer
	# g++ -Wall -g -std=c++17 test_sigpromask.cpp -o test_sigpromask
	g++ -Wall -g -std=c++17 test_sigsuspend.cpp -o test_sigsuspend

clean:
	@rm -rf test_sigaction test_cal_clock \
			test_cal_alarm test_print_sleep \
			test_print_alarm \
			test_print_setitimer \
			test_sigpromask \
			test_sigsuspend