all:
	g++ -Wall -g -std=c++17 test_trim.cpp -o test_trim
	g++ -Wall -g -std=c++17 test_split.cpp -o test_split
	g++ -Wall -g -std=c++17 test_stringformat.cpp -o test_stringformat

clean:
	rm -rf test_trim test_split test_stringformat