all:
	@# g++ -Wall -g -std=c++17 test_select.cpp -o test_select
	@# g++ -Wall -g -std=c++17 test_poll.cpp -o test_poll
	@# g++ -Wall -g -std=c++17 test_poll2.cpp -o test_poll
	g++ -Wall -g -std=c++17 test_epoll.cpp -o test_epoll
clean:
	rm -rf test.pipo test_select test_poll test_epoll